image: 'node:latest'

stages:
  - build
  - release

cache:
  paths:
    - node_modules/

build:
  stage: build
  variables:
    GITLAB_TOKEN: $CI_API_TOKEN
  before_script:
    - npm install -g semantic-release @semantic-release/gitlab @semantic-release/npm @semantic-release/gitlab-config conventional-changelog-conventionalcommits
  script:
    - semantic-release -e @semantic-release/gitlab-config
    - npm install -g pkg
    - npm install
    - pkg . -t node12-linux-x64 -o isxer
  artifacts:
    expire_in: 30 days
    paths:
      - isxer
  only:
    - master

release:
  stage: release
  variables:
    GITLAB_TOKEN: $CI_API_TOKEN
  before_script:
    - npm install -g semantic-release @semantic-release/gitlab @semantic-release/npm @semantic-release/gitlab-config conventional-changelog-conventionalcommits
    - cat $SEM_RELEASE_OPTIONS > .releaserc.yml
  script:
    - semantic-release -e @semantic-release/gitlab-config
  only:
    - master
